# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rspec-on-rails-matchers"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Taylor", "Stephen Schor", "Josh Knowles"]
  s.date = "2012-02-21"
  s.description = "Josh Knowles rspec-on-rails-matchers, upgraded for Rails 3+."
  s.email = ["scott@railsnewbie.com", "stephen@eastmedia.com"]
  s.extra_rdoc_files = [
    "README",
    "TODO"
  ]
  s.files = [
    ".rspec",
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "TODO",
    "VERSION",
    "lib/rspec_on_rails_matchers.rb",
    "lib/rspec_on_rails_matchers/associations.rb",
    "lib/rspec_on_rails_matchers/observers.rb",
    "lib/rspec_on_rails_matchers/validations.rb",
    "lib/rspec_on_rails_matchers/version.rb",
    "lib/rspec_on_rails_matchers/views.rb",
    "rspec-on-rails-matchers.gemspec",
    "spec/rspec-on-rails-matchers/associations_spec.rb",
    "spec/rspec-on-rails-matchers/validations_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/smtlaissezfaire/rspec-on-rails-matchers"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Rspec on rails matchers"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<rspec-rails>, [">= 2.6.1"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.6.1"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.6.1"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
  end
end

